import pyarrow as pa
import pyarrow.parquet as pq
import os
import logging

logger = logging.getLogger("cortex.vector_reader")

class MDFVectorReader:
    """
    Layer 8.1 - The Intelligence Link
    Reads the Molecular Data Format (MDF) generated by the Layer 2/4 pipeline.
    This bypasses the Grid Service for heavy ML workloads, reading directly from the Gold Tier (S3/Parquet).
    """
    
    def __init__(self, data_path: str = "/data/mdf"):
        self.data_path = data_path
        
    def load_molecule_vectors(self, app_id: str, scenario_id: str) -> pa.Table:
        """
        Loads the embedding vectors and values for a specific Application Scenario.
        In "Ultra-Diamond", this is a zero-copy operation using Apache Arrow.
        """
        file_path = os.path.join(self.data_path, app_id, f"{scenario_id}.parquet")
        
        if not os.path.exists(file_path):
            logger.warning(f"MDF file not found for {app_id}/{scenario_id}. Using simulated vectors.")
            return self._generate_simulated_table()
            
        try:
            # Zero-copy read from Parquet directly into PyArrow table
            table = pq.read_table(file_path)
            logger.info(f"Loaded {table.num_rows} atoms from MDF.")
            return table
        except Exception as e:
            logger.error(f"Failed to read MDF: {e}")
            raise

    def _generate_simulated_table(self) -> pa.Table:
        """
        Fallback for development before the Rust Data Spine is persistently writing to local disk.
        """
        import numpy as np
        
        # Simulate 1000 atoms with 128-dimensional embeddings
        num_atoms = 1000
        dims = 128
        
        ids = pa.array([f"atom_{i}" for i in range(num_atoms)])
        values = pa.array(np.random.randn(num_atoms) * 1000 + 5000) # Centered around 5k
        embeddings = pa.array([np.random.randn(dims).tolist() for _ in range(num_atoms)])
        
        return pa.Table.from_arrays([ids, values, embeddings], names=["atom_id", "value", "embedding_vector"])

# Singleton instance
vector_reader = MDFVectorReader()
