package orchestration

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"time"
)

// VarianceDriverItem matches the Python model
type VarianceDriverItem struct {
	Dimension         string  `json:"dimension"`
	Member            string  `json:"member"`
	ScenarioAVal      float64 `json:"scenario_a_val"`
	ScenarioBVal      float64 `json:"scenario_b_val"`
	Variance          float64 `json:"variance"`
	PercentageOfTotal float64 `json:"percentage_of_total"`
}

// SynthesisRequest matches the Python model
type SynthesisRequest struct {
	KPI           string               `json:"kpi"`
	TotalVariance float64              `json:"total_variance"`
	Drivers       []VarianceDriverItem `json:"drivers"`
}

// SynthesisResponse matches the Python model
type SynthesisResponse struct {
	Narrative         string  `json:"narrative"`
	AIConfidenceScore float64 `json:"ai_confidence_score"`
}

type FluxionClient struct {
	baseURL    string
	httpClient *http.Client
}

func NewFluxionClient(baseURL string) *FluxionClient {
	return &FluxionClient{
		baseURL: baseURL,
		httpClient: &http.Client{
			// The LLM query might take a few seconds
			Timeout: 10 * time.Second,
		},
	}
}

// SynthesizeVariance calls the Python RAG endpoint to generate the executive narrative
func (c *FluxionClient) SynthesizeVariance(ctx context.Context, tenantID string, req SynthesisRequest) (*SynthesisResponse, error) {
	url := fmt.Sprintf("%s/api/v1/narrative/variance", c.baseURL)

	payload, err := json.Marshal(req)
	if err != nil {
		return nil, fmt.Errorf("failed to marshal request: %w", err)
	}

	httpReq, err := http.NewRequestWithContext(ctx, "POST", url, bytes.NewReader(payload))
	if err != nil {
		return nil, fmt.Errorf("failed to create http request: %w", err)
	}

	httpReq.Header.Set("Content-Type", "application/json")
	// Pass the tenant ID down to bypass or enforce governance
	httpReq.Header.Set("X-Tenant-ID", tenantID)

	resp, err := c.httpClient.Do(httpReq)
	if err != nil {
		return nil, fmt.Errorf("fluxion http call failed: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		bodyBytes, _ := io.ReadAll(resp.Body)
		return nil, fmt.Errorf("fluxion returned error %d: %s", resp.StatusCode, string(bodyBytes))
	}

	var synthResp SynthesisResponse
	if err := json.NewDecoder(resp.Body).Decode(&synthResp); err != nil {
		return nil, fmt.Errorf("failed to decode response: %w", err)
	}

	return &synthResp, nil
}

// GoalSeekScenario represents a branch proposal generated by the AI
type GoalSeekScenario struct {
	BranchID          string  `json:"branch_id"`
	TopDownTarget     float64 `json:"top_down_target"`
	ConvergenceStatus string  `json:"convergence_status"`
	Iterations        int     `json:"iterations"`
	MaxError          float64 `json:"max_error"`
}

// ExecuteGoalSeek signals the Rust AtomEngine (via Arrow Flight or CGO) to run a parallel
// Gradient Descent solver on a background Git-Flow branch for scenario modeling.
func (c *FluxionClient) ExecuteGoalSeek(ctx context.Context, tenantID, baseBranch, dimension, member string, target float64) (*GoalSeekScenario, error) {
	// In the real system, this bypasses Python and hits the Rust AtomEngine directly
	// or hits Python which orchestrates the Rust Engine via Arrow IPC.

	// Simulated execution of the Rust Solver on a background thread
	time.Sleep(1 * time.Second) // Simulate Rust solving 1M variables in parallel

	return &GoalSeekScenario{
		BranchID:          fmt.Sprintf("fluxion-scenario-%s-%.0f", member, target),
		TopDownTarget:     target,
		ConvergenceStatus: "CONVERGED_SUCCESSFULLY",
		Iterations:        14,
		MaxError:          0.0001,
	}, nil
}
